// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var buildScreen, processManager, screen;
  process.stdin.setRawMode(true);
  buildScreen = require('./screen');
  processManager = require('./process_manager');
  screen = buildScreen();
  screen.render();
  processManager(screen);
}.call(this);
