// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var ansi, pty;
  pty = require('pty.js');
  ansi = require('./ansi');
  module.exports = function (window, command) {
    var history, term;
    term = pty.spawn(command, [], {
      name: 'xterm-color',
      cols: 40,
      rows: 6
    });
    history = '';
    term.on('data', function (data) {
      data = data.replace(/\r\r\n/gm, '\n');
      data = data.replace(/\r\n/gm, '\n');
      history = ansi.parse(history, data);
      return window.setContent(history);
    });
    term.on('error', function (error) {
    });
    term.on('exit', function () {
      return window.destroy();
    });
    return term;
  };
}.call(this);
