// Generated by CoffeeScript 2.0.0-beta8
void function () {
  var blessed, cache$, max, min, offsetLeft, offsetTop, pty;
  blessed = require('blessed');
  pty = require('./pty');
  cache$ = Math;
  min = cache$.min;
  max = cache$.max;
  offsetTop = 0;
  offsetLeft = 0;
  module.exports = function (screen, options) {
    var content, frame, title, window;
    if (null != options.top)
      options.top;
    else
      options.top = offsetTop += 4;
    if (null != options.left)
      options.left;
    else
      options.left = offsetLeft += 4;
    if (null != options.width)
      options.width;
    else
      options.width = 100;
    if (null != options.height)
      options.height;
    else
      options.height = 20;
    frame = blessed.box({
      parent: screen,
      top: options.top,
      left: options.left,
      width: options.width,
      height: options.height,
      border: { type: 'line' },
      style: {
        fg: 'lime',
        focus: { border: { bg: 'green' } }
      }
    });
    title = blessed.text({
      parent: frame,
      left: 2,
      content: ' ' + options.title + ' ',
      tags: true
    });
    content = blessed.box({
      parent: frame,
      scrollable: true,
      tags: true,
      content: options.content,
      top: 1,
      left: 1,
      width: options.width - 2,
      height: options.height - 2
    });
    frame.focus();
    window = {
      move: function (options) {
        if (null != options.y) {
          frame.top += options.y;
          frame.top = max(frame.top, 0);
        }
        if (null != options.x) {
          frame.left += options.x;
          frame.left = max(frame.left, 0);
        }
        return screen.render();
      },
      size: function (options) {
        if (null != options.y) {
          frame.height += options.y;
          frame.height = max(frame.height, 4);
          content.height += options.y;
          content.height = max(content.height, 2);
        }
        if (null != options.x) {
          frame.width += options.x;
          frame.width = max(frame.width, 7);
          content.width += options.x;
          content.width = max(content.width, 5);
        }
        return screen.render();
      },
      scroll: function (delta) {
        content.scroll(delta);
        return screen.render();
      },
      setContent: function (data) {
        content.setContent(data);
        content.setScrollPerc(100);
        return screen.render();
      },
      focus: function () {
        frame.focus();
        frame.setFront();
        return screen.render();
      },
      destroy: function () {
        screen.remove(frame);
        this.onRemove();
        return screen.render();
      },
      onRemove: function () {
      },
      onFocus: function () {
      }
    };
    frame.on('focus', function () {
      return window.onFocus();
    });
    window.term = pty(window, options.command);
    return window;
  };
}.call(this);
